[package]
name = "my-game"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "launchers/wasm",
    "launchers/native",
]

[dependencies]
# Core dependencies
bevy = "0.8.0"
log = "0.4.17"