[package]
name = "wasm-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

# Optimizations for WASM
[profile.release]
panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
my-game = { package = "my-game", path = "../.." }
wasm-bindgen = "0.2.82"
yew = "0.19.3"
yew-router = "0.16.0"

# Logging
log = "0.4.17"
console_error_panic_hook = "0.1.7"
console_log = { version = "0.2.0" }