name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TOOLCHAIN: stable

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cargo cache
      - name: Cargo cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: cargo

      # Install cargo deps
      - name: Pull Cargo dependencies
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: |
          rustup update
          cargo install trunk

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # Check cache for existing revision of build
      - name: Build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build-${{ hashFiles('./src') }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./index.html') }}

      # Build release version
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          trunk build
