name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache build environment
      - name: Check setup tools
        id: cache-setup
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Install cargo deps
      - name: Pull Cargo dependencies
        if: steps.cache-setup.outputs.cache-hit != 'true'
        run: |
          rustup update
          cargo install trunk

  clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull setup tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Enforce Clippy lints, deny warnings
      - name: Clippy
        run: |
          apt install libasound2-dev libudev-dev pkg-config
          cargo clippy -- -D warnings

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull setup tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Check cache for existing revision of build
      - name: Build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build-${{ hashFiles('./src') }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./index.html') }}

      # Checkout code
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3

      # Build release version
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          trunk build
