name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache build environment
      - name: Check setup tools
        id: cache-setup
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Install cargo deps
      - name: Pull Cargo dependencies
        if: steps.cache-setup.outputs.cache-hit != 'true'
        run: |
          rustup update
          cargo install trunk

  clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull setup tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Enforce Clippy lints, deny warnings
      - name: Clippy
        run: |
          sudo apt install libasound2-dev libudev-dev pkg-config
          cargo clippy --workspace -- -D warnings

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull setup tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Execute unit tests
      - name: Test
        run: |
          sudo apt install libasound2-dev libudev-dev pkg-config
          cargo test --workspace

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            "wasm32-unknown-unknown",
            "x86_64-unknown-linux-gnu",
            "x86_64-apple-darwin",
            "x86_64-pc-windows-gnu",
          ]
    steps:
      - name: Pull setup tools
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
          key: setup

      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ matrix.target }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}

      # Build release version
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build native
        if: |
          steps.cache-build.outputs.cache-hit != 'true' &&
          matrix.target != "wasm32-unknown-unknown"
        run: |
          sudo apt install libasound2-dev libudev-dev pkg-config
          cargo build --workspace --target ${{ matrix.target }}
      - name: Build web assembly
        if: |
          steps.cache-build.outputs.cache-hit != 'true' &&
          matrix.target == "wasm32-unknown-unknown"
        run: |
          trunk build
