name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-native:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: ${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}

      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3

      - name: Get Linux dependencies
        if: |
          steps.cache-build.outputs.cache-hit != 'true' &&
          matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Build
        if: |
          steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cargo build --workspace

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./launchers/wasm/dist
          key: WASM-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}

      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3

      - name: Install Trunk
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - name: Trunk Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: trunk build
