name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  RELEASE_NAME: my_game

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-tag.outputs.VERSION }}
    steps:
      - name: Get tagged version
        id: version-tag
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-windows-${{ needs.setup.outputs.version }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build --release

  build-mac:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-mac-${{ needs.setup.outputs.version }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build --release

  build-ubuntu:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-ubuntu-${{ needs.setup.outputs.version }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/native
          cargo build --release

  build-wasm:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./launchers/wasm/
          key: release-wasm-${{ needs.setup.outputs.version }}
      - name: Checkout code
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
      - name: Install Trunk
        if: steps.cache-build.outputs.cache-hit != 'true'
        uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"
      - name: Trunk Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd ./launchers/wasm
          trunk build

  release-windows:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-windows-${{ needs.setup.outputs.version }}
      - name: Rename build
        run: |
          mv ./target/release/native-launcher.exe ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.windows.exe
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.windows.exe

  release-mac:
    needs: build-mac
    runs-on: ubuntu-latest
    steps:
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-mac-${{ needs.setup.outputs.version }}
      - name: Rename build
        run: |
          mv ./target/release/native-launcher ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.darwin
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.darwin

  release-ubuntu:
    needs: build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: ./target
          key: release-ubuntu-${{ needs.setup.outputs.version }}
      - name: Rename build
        run: |
          mv ./target/release/native-launcher ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.linux
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: ./${{ env.RELEASE_NAME }}-${{ needs.setup.outputs.version }}.linux

  release-github-pages:
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: ./launchers/wasm/
          key: release-wasm-${{ needs.setup.outputs.version }}
      - name: Deploy, Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./launchers/wasm/dist/

  release-docker-server:
    needs: build-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Pull cache
        uses: actions/cache@v3
        with:
          path: ./launchers/wasm/
          key: release-wasm-${{ needs.setup.outputs.version }}
      # Qemu is an emulator for alternative architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Buildx allows us to build for several architectures
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Login to DockerHub - Setup your secrets! Check out the README.
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Push HTTP server Docker image
      - name: Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./launchers/wasm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.RELEASE_NAME }}:${{ needs.setup.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.RELEASE_NAME }}:latest
