name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Try to skip build
      - name: Pull build cache
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./target
          key: ubuntu-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('./src') }}-${{ hashFiles('./launchers') }}
      # Build
      - name: Get dependencies
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: sudo apt install libasound2-dev libudev-dev pkg-config
      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: cargo build --workspace

      # Unit testing
      - name: Test
        run: cargo test --workspace
