name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Unit testing
      - name: Test
        run: |
          sudo apt install libasound2-dev libudev-dev pkg-config
          cargo test --workspace
